- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip

    - name: Install MySQK Database
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: MySQL
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db: name=employee_db state=present

    - name: Create Database User
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install Python Flask dependencies
      pip:
        name: "{{ item }}"
        status: present
      with_items:
        - flask
        - flask_mysql

    - name: Copy source code
      copy: src=app.py dest=/opt/app.py

    - name: Start Web server
      shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &
